# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VIVADO/Basys-3-Master.xdc

# Block Designs: bd/exp2/exp2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2 || ORIG_REF_NAME==exp2} -quiet] -quiet

# IP: bd/exp2/ip/exp2_clk_mgnmnt_0_0/exp2_clk_mgnmnt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_clk_mgnmnt_0_0 || ORIG_REF_NAME==exp2_clk_mgnmnt_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_counter_0_0/exp2_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_counter_0_0 || ORIG_REF_NAME==exp2_counter_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_generador_seno_0_0/exp2_generador_seno_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_generador_seno_0_0 || ORIG_REF_NAME==exp2_generador_seno_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_mux_0_0/exp2_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_mux_0_0 || ORIG_REF_NAME==exp2_mux_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_Comparador_0_0/exp2_Comparador_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_Comparador_0_0 || ORIG_REF_NAME==exp2_Comparador_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_counter_1_0/exp2_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_counter_1_0 || ORIG_REF_NAME==exp2_counter_1_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_modular_clk_div_0_0/exp2_modular_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_modular_clk_div_0_0 || ORIG_REF_NAME==exp2_modular_clk_div_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_uart_rx_0_0/exp2_uart_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_uart_rx_0_0 || ORIG_REF_NAME==exp2_uart_rx_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_modular_clk_div_1_0/exp2_modular_clk_div_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_modular_clk_div_1_0 || ORIG_REF_NAME==exp2_modular_clk_div_1_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_OR_0_0/exp2_OR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_OR_0_0 || ORIG_REF_NAME==exp2_OR_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_ss_driver_0_0/exp2_ss_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_ss_driver_0_0 || ORIG_REF_NAME==exp2_ss_driver_0_0} -quiet] -quiet

# IP: bd/exp2/ip/exp2_display_voltaje_0_0/exp2_display_voltaje_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp2_display_voltaje_0_0 || ORIG_REF_NAME==exp2_display_voltaje_0_0} -quiet] -quiet

# XDC: bd/exp2/exp2_ooc.xdc
